### ISSUE TITLE
Missing file in BMMCVignette

### ISSUE THREAD

**Issue by smorabit** [HYsxe/PRINT#1]
Hi Yan,

First of all what an exciting new method for TF analysis! 

I was trying to go through the [BMMCVignette](https://github.com/HYsxe/PRINT/blob/main/analyses/BMMCTutorial/BMMCVignette.pdf), and I encountered a problem with a missing data file pretty early in the vignette.

On this line, 

```
regionsBed <- read.table(paste0(projectDataDir, "BMMCTutorialRegions.bed"))
```

where `projectDataDir = "../../data/BMMCTutorial/"`

It seems like in the [data folder](https://github.com/HYsxe/PRINT/tree/main/data) there is not a directory called `BMMCTutorial`, and I don't see the `.bed` file in any of the other folders. Hopefully a simple fix if you could add the missing file.

Thanks,
Sam

**Comment by clip78** [comment]
Hi,

I was also going through the tutorial and noticed that the "precomputedTn5Bias" folder is not in "data/shared" that should contain the "predBias.rds" file. Looks like an interesting approach for footprinting!

Thanks,
Clay

**Comment by HYsxe** [comment]
Hi! Thanks for the question!

I just uploaded the tutorial data. Could you see if you can access them now?

**Comment by HYsxe** [comment]
> 

So the predBias.rds is computed for each new data set using the getPrecomputedBias function in the tutorial. To run this function, you need to download the pre-computed bias files from https://zenodo.org/record/7121027#.ZCbw4uzMI8N and put it in the data/shared/precomputedTn5Bias folder. Could you try that and let me know if you run into any issues? Thanks!

**Comment by clip78** [comment]
Yes, I see the BMMC tutorial files. OK, I understand now about the predBias file now. I'm downloading the hg38 bias file and will try it out. Thanks for your help!

**Comment by clip78** [comment]
The tutorial code seems to be working fine now. I found one issue that the "BMMCTutorialRegions.bed" file did not have a header, so the the read.table function created V1:V3 colnames. The next command creating the granges object, used "chr", "start", and "end" for the colnames. After fixing that and getting a few packages installed, it was working until I got to the pseudobulk files. I can't seem to find the "pseudobulkATAC.rds" or "pseudobulkRNA.rds" files.

**Comment by HYsxe** [comment]
Those files are a bit big and can't be uploaded to github. I just put them on our zenodo repo at https://zenodo.org/record/7790194#.ZCdmP-zMJTY. It's the BMMCTutorial.tar.gz file. Could you give it a try?

Thanks!

**Comment by clip78** [comment]
Great. Yes, I got the files and was able to complete the rest of the tutorial. Thanks for your help. Excited to try this on my data now, but I think this issue can be closed.

Cheers

**Comment by HYsxe** [comment]
Good to know! Hope our work is helpful for you : )
