### ISSUE TITLE
getFootprints error

### ISSUE THREAD

**Issue by mfrenkel16** [HYsxe/PRINT#11]
Hi,

I am running into an error when running the tutorial on the BMMCTutorial data. Everything works up until `getFootprints` which produces the error: Error in { : task 6 failed - "$ operator is invalid for atomic vectors"

<img width="735" alt="Error" src="https://github.com/HYsxe/PRINT/assets/91026492/2a9ecb3f-8f9a-438e-b290-7b76369ba3cd">

I'm running the tutorial interactively in a job with an apptainer that has the dependencies needed. In case you wanted to build the extact container I'm using, I've attached the def file below). I'm using R version 4.2.1. The code that I'm using is attached below "Reproducible_Tutotiral_R_Code.txt". The command that fails is `scale <- 50
project <- getFootprints(
project,
mode = as.character(scale),
nCores = 16,
footprintRadius = scale,
flankRadius = scale)`

Everything before this runs ok. There is a Warning for `loadTFBSModel` that "TF-TRT Warning: Could not find TensorRT" but I'm not sure this matters. I'm not using a GPU for this.

Here's the traceback:

<img width="737" alt="Traceback" src="https://github.com/HYsxe/PRINT/assets/91026492/bafa2f2a-23fc-4336-81e2-2ad85c57555f">

Here's the code which starts in the interactive job outside of R, establishes the environment, and then enters R: 
[Reproducible_Tutorial_R_Code.txt](https://github.com/HYsxe/PRINT/files/11616221/Reproducible_Tutorial_R_Code.txt)

And if you want to build the apptainer I'm using, here's the def file:

Please let me know if you need any other information or if you know how to fix this.

Thanks!
Max

**Comment by mfrenkel16** [comment]
[msfprint.def.txt](https://github.com/HYsxe/PRINT/files/11617034/msfprint.def.txt)
I forgot to upload the def file for the apptainer in case you wanted to build it, but I don't think the error has to do with this and instead has to do with something in R and the getFootprints code.

**Comment by HYsxe** [comment]
Hi Max!

Sorry for the late reply. I remember seeing my lab mates ran into this and I vaguely remember it was a R or package version issue. If you try using R4.1.0 do you still get the error?
