### ISSUE TITLE
Pseudo-bulk generation issue with SEACells

### ISSUE THREAD

**Issue by OMIC-coding** [HYsxe/PRINT#15]
Dear you,
I noticed you implemented SEACells to generate pseudo-bulk for scATAC. However, there is a parameter (waytpoint_proportion) in SEACells.ipynb which cannot be recognized in SEACells.core.SEACells function. I also encountered a bug as follows when I conducted the SEACells.core.SEACells function:
AttributeError: "NoneType" object has no attribute 'shape'
So, I guess if you add this specific parameter to solve the same bug. Could you help me with that?

**Comment by OMIC-coding** [comment]
I think you omitted a step (model.construct_kernel_matrix()) before model.initialize_archetypes(). It would be nice to correct that mistake of your code script.

**Comment by HYsxe** [comment]
Hi!

I suspect that their code has been upgraded because we were able to run the version you saw in our github. I do, however, need to double check to be sure. Our lab is currently experiencing a cluster outage and we will get back to you as soon as I regain access.

**Comment by HYsxe** [comment]
Sorry for the late reply! I think SEACells have indeed changed their functions. I tried running the newest version of SEACells and indeed you can't run initialize_archetypes before running model.construct_kernel_matrix(). I believe this was not the case for the original version I was running on. Thans for pointing this out!
