### ISSUE TITLE
cell number in BMMC

### ISSUE THREAD

**Issue by gewoods** [HYsxe/PRINT#16]
Hi Yan, 
I just noticed that there are about 800,000 cells in total in your BMMC datasets, while you have 1000 pseudobulks and each contains 5000 cells in the tutorial. Just wondering is there any reason to have same cells in different pseudobulks? Thanks!

**Comment by HYsxe** [comment]
Hi!

This is similar to running a sliding window / running window type of analysis across pseudo-time. We were mostly hoping to capture different stages of differentiation. Theoretically you can of course do pseudo-bulking without any overlapping cells and it has worked well for us in many cases.

Yan
