### ISSUE TITLE
Tn5 bias for non-human/mouse genomes

### ISSUE THREAD

**Issue by plantformatics** [HYsxe/PRINT#2]
I could not find code to produce a new Tn5 bias model for my model species (maize). Any advice on how to go about this? Looks like a great tool!

**Comment by HYsxe** [comment]
Hi! You can take a look at https://github.com/HYsxe/PRINT/tree/main/analyses/refGenomeTn5Bias. You need to put your .fa file in the instructed folder. Making genome-wide prediction for a new genome takes a few days to run on my side but once it's done you don't need to run it again. Hope this helps!

**Comment by plantformatics** [comment]
Yup, I saw that earlier and I am running that right now (I couldn't find the SHARE_footprinting conda env, so getting all the required library versions installed was a little bit painful). However, I also have my own high coverage Tn5-treated gDNA sample and was thinking to train a new model. Will there be a future update to guide others how to do this? Would such a new model actually learn anything that the BAC-based model hasn't already (i.e. is this a waste of time)? 

Thanks again for producing this new tool, I feel that it will be a game changer and set a new standard in how single-cell chromatin accessibility data is analyzed.

**Comment by HYsxe** [comment]
Thank you for the kind words and sorry the installation thing is a pain. Let me take a look to see what's the best way for me to share the environment. Meanwhile, I have uploaded a requirements.txt to the /code folder. Maybe you can give it a try? I have helped others in the lab set up on their computers but I'm aware sometimes you can run into system/environment differences. Keep me posted!

**Comment by plantformatics** [comment]
I was able to install all the dependencies and the code is running (looks like it will finish in 1.5 days at the current pace). The requirements file will definitely help others! Thanks for getting back to me so quickly.

**Comment by HYsxe** [comment]
That's great to hear! We have tested on naked DNA from different sources and the model seemed to have learned pretty consistent bias patterns (data to be released). Nonetheless, it would still be interesting to run our code on new naked DNA data to see in what conditions the model is generalizable or not. If you are trying this, I would recommend you to take a close look at how we shift ends of ATAC reads because that would have a huge impact on the result.

**Comment by plantformatics** [comment]
Good to hear that the models have been consistent so far. At the end of the day, its an enzyme on DNA, and the source of DNA should have no impact (unless there are sequence contexts that are dramatically different, which I don't think is the case). I have always used +4/-5 for 0-based coordinates. Is there a different processing practice that you'd recommend? Thanks again for the information and willingness to help. I can't wait to see how your footprinting approach fairs on my data set!

**Comment by HYsxe** [comment]
I believe +4/-4 is more correct! Say Tn5 cutting generates the 9bp staggered end ATCGTCGAT as [0, 9) (0-based indexing), then +4/-4 gives you [4,5) which is the symmetry center T of the 9bp. +4/-5 gives you [4, 4) which is not quite right because the right side goes over by 1bp.

**Comment by plantformatics** [comment]
Makes sense - I'll adjust to +4/-4 for this analysis. Thanks for the tip!

**Comment by plantformatics** [comment]
Quick update on the bias h5 files: I was able to create the reference bias h5 files, but am running into an issue loading it with PrecomputedBias. The progress bar goes to completion, but then I see this error:

`Error in data.table::rbindlist(refBias) :
  Item 1089 has 43 columns, inconsistent with item 1 which has 100 columns. To fill missing columns use fill=TRUE.`
  
 Any suggestions on how to address it?

**Comment by plantformatics** [comment]
I fixed the above error by setting `fill=TRUE` in the call to rbindlist. But then I got the error `Error in regionRanges(project) : object 'project' not found` when saving the refBias object to the `regionBias` slot of the project object. I fixed that bug by replacing all instances of `project` with `x` within the function (the function specified "x", and "value" as input, no mention of "project" variable in the local scope). Finally, I am left with the error: 

`Error in regionBias<-(*tmp*, value = refBias) : Number of regions in region ranges and region bias don't match`
  
I suspect this comes from the original "fix" that I did by adding `fill=TRUE` to rbindlist. I guess that item 1089 is the last chunk of the bias h5 file. Thanks again for your help - making this approach broadly accessible (pun intended) will be useful for many researchers in the future!

**Comment by plantformatics** [comment]
For what it's worth, `dim(value)[1]` is equal to 1089100, and `length(regionRanges(x))` is equal to 108843. The length of regionRanges(project) is the number of accessible chromatin regions (cCREs as you call them in the preprint), so I guess that the error is coming from how the bias file is loaded?

**Comment by plantformatics** [comment]
OK I think im getting close to figuring this out. Are the broad regulatory regions (loaded by regionRanges) all expected to be the same size, i.e. 1 kilobase? 

Update: Fixing the interval size of the regionRanges to 1kb fixed the issue.

**Comment by HYsxe** [comment]
Yes! Sorry we didn't make that clear in the tutorial. The genomic regions for footprinting should be resized to the same size. This is because we store the pre-computed bias for a project in the form of a region-by-position matrix for fast retrieval. If the regions are not the same size it can't be formatted into a matrix. Glad you mentioned that. We will add this to our tutorial later.
