### ISSUE TITLE
Path to h5 file

### ISSUE THREAD

**Issue by CebolaLab** [HYsxe/PRINT#23]
Line 105 of the getBias.R script specifies the h5 file path using `../..` which caused an error since I was working in a different directory and providing full paths. The below edit fixed the problem:

`h5_path <- paste0(projectMainDir,"data/shared/precomputedTn5Bias/", referenceGenome, "Tn5Bias.h5")`

**Comment by HYsxe** [comment]
Thanks for the question!

Yeah the current version of code requires a specific folder structure. You can change the path to your own location storing the precomputed Tn5 bias files. New files can be downloaded here https://zenodo.org/records/13963610

We will soon provide a new re-implemented python version of PRINT which solves this problem and automatically load the Tn5bias. Thanks for the suggestion!
