### ISSUE TITLE
Plot footprints by group

### ISSUE THREAD

**Issue by CebolaLab** [HYsxe/PRINT#25]
Hello, I'm wondering if there's an easy way to separate the footprint plots by group (sorry if I've missed how to do this, I've had a dig through the code and tutorials). I'm using bulk RNA-seq data from two conditions/groups. Using the code `plotMultiScale(project = project, regionInd = i, kernelSizes = 2:100)`, can I subset the data to create two plots from each group? I'd like to visualise the multi-scale footprinting side-by-side. 

I suppose one option is to rerun the pipeline for each group seperately, but is there a way to pull the relevant data out of the project?

Many thanks!

**Comment by HYsxe** [comment]
Thanks for the question! Yes you should be able to only use a subset of cells to make this plot.

The fucntion plotMultiScale has an argument called lineageGroups, which was originally designed to select pseudo-bulks for specifci differentiation lineages for plotting. However, here you can just use it to keep desired pseudo-bulks for making your plot.

For more details, you can take a look at this function at line 595 and 604 in https://github.com/HYsxe/PRINT/blob/main/code/visualization.R

```
setGeneric("plotMultiScale", function(project,# footprintingProject object
                                          regionInd, # Integer. Index of the region to plot
                                          lineageGroups = NULL, # IDs of the pseudobulks to plot
                                          kernelSizes = 2:100, # footprint radii to use for multi-scale footprinting
                                          smoothRadius = 5 # Radius for smoothing
                                          ) 
```

For this argument you should be able to just provide the subset of pseudobulk IDs same as those in barcodeGroups$group and use it to filter data. 

Let me know if this works for you and I'll be happy to help you debug further!

**Comment by CebolaLab** [comment]
Brilliant! Just what I was looking for. Thanks for the help and sorry for not catching this.
