### ISSUE TITLE
Package dependency for BuenRTools

### ISSUE THREAD

**Issue by cemmeydan** [HYsxe/PRINT#5]
Hi,
Various functions and scripts (filterPeaks, filterFrags etc.) reference the BuenRTools library, which I couldn't find in Buenrostro lab or any other place. Is it available anywhere? Or Is there at least a description of the methods to replicate the code?

Thank you,

**Comment by HYsxe** [comment]
Hi!

Thanks for pointing this out! I will add those functions to our code base and let you know when I'm done!

**Comment by HYsxe** [comment]
Ok I have added those functions to utils.R and updated references to these functions in other scripts. Could you give the updated codes a try?

**Comment by cemmeydan** [comment]
Thank you. 

- Searching the repo few functions still seem to be missing or referencing the BuenRTools.  `summitsToCleanPeaks`, `splitAndFetch`, `BuenRTools::mm10TSSRanges`, etc. I do not know if this is the complete set, or how critical they are for the functionality, just what I noticed so far.

Also few small issues that were trivial to fix.

- `library(BuenRTools)` command is still present, causing an error when the package is missing.

- Some of the functions are defined in utils.R, but are still referenced from `BuenRTools` in a couple of the example scripts, e.g. `BuenRTools::getCountsFromFrags`, `BuenRTools::getGeneScoresFromPeaks`, `BuenRTools::centerCounts` etc. 

- source for util and the file paths are relative, e.g. `source("../../code/utils.R")`, `chrSizes <- "../shared/mm10.chrom.sizes"` 
However when the Rscript command is run from another working directory (i.e. path of the bam files) it fails to find these files. `Rscript /path/to/PRINT/code/...` ). I used https://stackoverflow.com/a/15373917 to get the path of the R file to make the paths relative to the script file and not the working directory and that seems to work.

Thank you,

**Comment by HYsxe** [comment]
I have just updated the above BuenRTools references and now just doing a quick search I think there shouldn't be any BuenRTools:: left. And yeah I think the most ideal case would be to make this into a package which is still on our to-do list. For the current version, we have a recommended folder structure in our tutorial. I think if you try that it should be able to find all the files. Let me know if these updates work!
