### ISSUE TITLE
Using PRINT with bulk ATAC-seq data?

### ISSUE THREAD

**Issue by maxdudek** [HYsxe/PRINT#6]
Hi, 

The vignette tutorial is very helpful, but it looks like it assumes we have single cell samples assigned to pseudo-bulks. Is it possible to use PRINT on bulk `.bam` files? If so, how would you recommend transforming the bams into the `.tsv` fragment file that PRINT expects? 

I think this tool is the best footprinting method out there and I'm really eager to use it, so any advice would be greatly appreciated.

Thanks!

**Comment by HYsxe** [comment]
Hi!

Thank you for your interest in our work! Here's a simplified version of the code that we use to convert bams to fragment files

```

# You need to first name sort the bam file
echo "Name sorting bam file"
samtools sort -n -@ $cores -o $sorted_bam $bam_file

# Then convert to fragments file using bamtobed -bedpe
echo "Converting bam file to fragments file"
bedtools bamtobed -i $sorted_bam -bedpe | \
sed 's/_/\t/g' | \
awk -v OFS="\t" '{if($10=="+"){print $1,$2+4,$6-5,$8}}' |\
sort --parallel=$cores -S 40G  -k4,4 -k1,1 -k2,2n -k3,3n | \
uniq -c | \
awk -v OFS="\t" '{print $2, $3, $4, $5, $1}' | \
gzip > $frags_name
```

Note that theoretically +4/-4 shift of the fragment ends is correct, but since many previous studies have done +4/-5, this pipeline also follows this convention and do +4/-5 shift. When you use PRINT to load it, PRINT will internally convert it to +4/-4.

Here's a document briefly explaining the code. Apologies it's not well formatted

[Getting fragment files from bams.pdf](https://github.com/HYsxe/PRINT/files/11344497/Getting.fragment.files.from.bams.pdf)

Hope this helps!

**Comment by mspivakov** [comment]
Thanks a lot for this from me as well! Can you please advise how then to plug this tsv into the analysis code (using the tutorial as an example)? Am I right that it should be provided to getCountTensor()? What should I use as the barcodeGroups in this case?

**Comment by HYsxe** [comment]
Yes you are right! barcodeGroups is essentially just a table with two columns keeping the barcodes and the group labels. If you have, say, a single fragments file from one bulk sample, then you can just replace the single cell barcode in the fragments file (4th column) of each fragment with the bulk sample ID, for example "bulk_rep 1". And barcodeGrouping.txt can just be one row of ("bulk_rep_1", "group_1"). The script at https://github.com/HYsxe/PRINT/blob/main/analyses/K562/main.R uses K562 single cell data and treat it as a bulk sample. It might be helpful for you.

**Comment by mspivakov** [comment]
Thanks a lot, this is very helpful!

**Comment by maxdudek** [comment]
Thanks for the reply!

**Comment by lhqing** [comment]
Hi Yan, thanks for your answer!

I think the command you had on this issue only dealt with "+" strand, but the "-" strand is missed. Your pipeline.sh file in the K562 example was correct through. Is it correct?

https://github.com/HYsxe/PRINT/blob/6c1c58cb6ed8a5e3dcab84435c131c4eeedadc2b/data/K562/pipeline.sh#L82

**Comment by HYsxe** [comment]
Hi Hanqing,

In fact both examples are correct! In the "[Getting fragment files from bams.pdf](https://github.com/HYsxe/PRINT/files/11344497/Getting.fragment.files.from.bams.pdf)" I posted above, you can see that by this step the data is in bedpe format. In the vast majority of the rows (>95%), the 10th and 11th columns should be "+" and "-" respectively. This is the usual case when your forward reads is upstream of the reverse read. In this case, a simple +4/-5 shift should suffice (the correct shift is +4/-4, but to conform with the field standard here we do +4/-5 first and then later the package will do a +0/+1 to make it +4/-4). In very few cases, there will be some rows where the 10th and 11th columns will be "-" and "+". Some of our labmates looked into it and our best guess at the moment is that in those cases the two Tn5 insertions of the same fragment are too close to each other, so when you sequence, the reverse read goes past the forward insertion site and ends up up upstream of the forward read. You can choose to either keep these rare events by doing 

`awk -v OFS="\t" '{if($10=="+"){print $1,$2+4,$6-5,$8}else if($10=="-"){print $1,$2-5,$6+4,$8}}'`

or filter out these events by doing

`awk -v OFS="\t" '{if($10=="+"){print $1,$2+4,$6-5,$8}}'`

In theory, if the two Tn5s are too close to each other the steric hindrance might affect their cutting bias and affect footprint calling so it might be desirable to filter out these rare events. In practice we haven't observed a significant difference either way probably because these events are rare.

Hope this helps!

Yan

**Comment by lhqing** [comment]
Thank you @HYsxe for the details and great insights!!

Yes you are right, the data I'm looking at also has majority R1 being at "+" and R2 being "-". I'll follow your choice for now.

**Comment by maxdudek** [comment]
Thanks for the explanation @HYsxe !

Looking at my .bedpe, I see some lines where both ends of the pair are aligned to the same region, e.g.

```
7       132133736       132133815       7       132133736       132133815       A00252:121:H37W2DSXY:1:1101:1063:29199  60      -    +
```

My guess is that this happens when the fragment is so small that both reads cover the entire fragment. But since strand1 is "-" here, I'm not sure that the "$2-5,$6+4" correction would be valid here - do you have any insights into what's going on and how I should transform these pairs? Glancing at the first ~100 pairs this seems to be pretty common, so I'm hesitant to just ignore them. Thanks!

**Comment by HYsxe** [comment]
I think the best way to determine whether to keep these reads would be to check their Tn5 bias. For any shifting you want to test, you can retrieve the DNA sequence context of each fragment after shifting, then aggregate these sequences to get a PWM (although PWMs are rather simplified models, they can help you catch cases where the bias is changed drastically). You can get the PWMs of the above cases (entries where the two reads look the same) and other cases (the regular + - ones) and compare whether the PWM in general looks similar. You raised a good point that in certain cases the $2-5,$6+4 is not applicable. In your particular case it should still be $2+4,$6-5. 

What is the percentage of these edge cases in your whole file? If it's not high I would recommend holding off on including them until we figure out the best practice for this scenario.

Thanks!

**Comment by maxdudek** [comment]
@HYsxe Thanks for the response! 

Here is the breakdown of pairs in the whole bedpe file (as percentages):
```
                    strand1
                    +     -    Sum
different reads  69.5   0.4   69.9
same reads       15.1  15.1   30.1
Sum              84.6  15.4  100.0
```

So it looks like 30% of the file is pairs with two identical regions, where the strand is randomly selected. This is enough that I need to look into it further, I'll run the PWM analysis and get back to you.

**Comment by maxdudek** [comment]
I did what @HYsxe suggested regarding PWMs and am showing my results here in case anyone has a similar issue. For each coordinate of interest, I extracted the sequence context +/-15 bp on either side to construct a 31 bp sequence logo. 

First, for a negative control, I looked at the start of read 2 and the end of read 1 (these should have nothing to do with Tn5 insertion):
![image](https://github.com/HYsxe/PRINT/assets/36005725/46a5971a-3b5a-41be-b27a-7d0ce4ed6bec)
![image](https://github.com/HYsxe/PRINT/assets/36005725/e848e920-8804-4f61-a7a4-7875d3cc6756)

Next, as a positive control, I looked at the start of read 1 for fragments with different reads, on the + strand (the upstream end of the Tn5-cut fragment). These fragments are 69.5% of the file:
![image](https://github.com/HYsxe/PRINT/assets/36005725/68ac6d47-1960-4156-81ba-0cc393ad8c37)
Assuming the cutsite is at position 20, this corresponds to a cut which is +4 bp compared to the start (center = position 16). 
And here's the end of read 2 for these fragments, i.e. the downstream end:
![image](https://github.com/HYsxe/PRINT/assets/36005725/0afefc93-9bf5-4102-87b1-83a140511e87)
Again, if the cut is at position 11, this is -5 compared to the end, as expected. 

0.4% of fragments have different reads but occur on the - strand. Here are the PWMs for the start and the end of these fragments:
![image](https://github.com/HYsxe/PRINT/assets/36005725/8d450743-3d36-4752-ab47-9f1a1daf9251)
![image](https://github.com/HYsxe/PRINT/assets/36005725/778b7280-8f7d-4595-8515-6f8bf35d4508)
These look weird, but I think we're seeing both a +4 _and_ a -5 cut here, since positions 16 and 17 have high information content in both. I'm not really sure though, so I'll probably filter these out.

So, what about those weird fragments where both reads in the pair align to the same region (the other 30.1%)? 
Well, regardless of which strand they appear on, we see the same +4/-5 shift as in the positive control:
![image](https://github.com/HYsxe/PRINT/assets/36005725/40867bcd-3130-4586-98e4-a3ad7c4c3d86)
![image](https://github.com/HYsxe/PRINT/assets/36005725/0105f442-5fdf-4573-b971-79a49d6492d0)
![image](https://github.com/HYsxe/PRINT/assets/36005725/48a92890-2ef1-4675-8e0e-1cc16213a91f)
![image](https://github.com/HYsxe/PRINT/assets/36005725/e9bd76e6-37c0-4704-84f4-9791d31c882c)

My conclusion is that these fragments are true Tn5-cut fragments, which are so small that they end up being completely sequenced by both reads in the pair, and are arbitrarily assigned a strand. Therefore, I'm including them in my analysis with the standard +4/-5 transformation.

**Comment by HYsxe** [comment]
Thank you @maxdudek for this very insightful result! Yeah it seems like those short fragments are indeed true Tn5 fragments. I guess their percentage is higher than what I'd expect. How many cycles are you sequencing? If you are sequencing very long reads that could explain the differences we see.

I really like the PWMs you showed! Just wondering what index (1-based index vs 0 based-index) did you use for the above plots? It seems that your "diff_reads.strand+.start1" is shifted to the right by 1 base. Any chance you used the 0-based indexing from your bed coordinates and then used 1-based indexing which is standard for python? When you combine the forward and reverse strand bias, it should look symmetric like Figure S1a in our preprint.

Hope this helps :)

**Comment by maxdudek** [comment]
@HYsxe So we have 150 bp paired end reads, if that's what you mean by cycles (apologies, I'm not very familiar with sequencing parameters). 

As for the off-by-one error, it's definitely because I used R with 1-based indexing. I wasn't too concerned about this because I really just wanted to know the direction (+4 or -5), and I figured that would give me enough info. Thank you!

**Comment by HYsxe** [comment]
I think that explains it! We always use 38 or 50 bp paired end reads so that might be why we have been getting pretty low number of pairs where it sequences through the whole fragment! Thanks for pointing out this issue and it's very useful for us too!
